Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -68,13 +68,49 @@ jobs:
           CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
           REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
 
+  publish_firefox:
+    name: Publish to Firefox Add-ons
+    needs:
+      - build
+    runs-on: ubuntu-latest
+    outputs:
+      publish_status: ${{ steps.publish-firefox.outputs.publish_status }}
+    steps:
+      - name: Checkout source
+        uses: actions/checkout@v2
+
+      - uses: actions/setup-node@v2
+        with:
+          node-version: 14
+
+      - name: Install packages
+        run: npm install
+
+      - name: Download artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: build
+          path: build
+
+      - name: Upload
+        id: publish-firefox
+        continue-on-error: true
+        run: |
+          npm run release:amo
+          echo "::set-output name=publish_status::${?}"
+        env:
+          WEB_EXT_API_KEY: ${{ secrets.API_KEY }}
+          WEB_EXT_API_SECRET: ${{ secrets.API_SECRET }}
+
   statuses:
     name: Checks statuses
     needs:
       - publish_chrome
+      - publish_firefox
     runs-on: ubuntu-latest
     steps:
       - name: Publish statuses
         run: |
           echo "::warning::Chrome publish status: $([[ "${{ needs.publish_chrome.outputs.publish_status }}" = "0" ]] && echo 'SUCCESS' || echo 'FAILED')"
-          [["${{ needs.publish_chrome.outputs.publish_status }}" != "0" && "${{ needs.publish_chrome.outputs.publish_status }} != "0"]]; then exit 1; fi
+          echo "::warning::Firefox publish status: $([[ "${{ needs.publish_firefox.outputs.publish_status }}" = "0" ]] && echo 'SUCCESS' || echo 'FAILED')"
+          [["${{ needs.publish_chrome.outputs.publish_status }}" != "0" && "${{ needs.publish_firefox.outputs.publish_status }} != "0"]]; then exit 1; fi
